// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PutniNalogDataContext.PN.Database;

#nullable disable

namespace PutniNalogDataContext.PN.Migrations
{
    [DbContext(typeof(PNDbContext))]
    partial class PNDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.PN.Model.MjestoPutovanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NazivMjesta")
                        .HasColumnType("text")
                        .HasColumnName("naziv_mjesta");

                    b.HasKey("Id");

                    b.ToTable("mjesto_putovanja");
                });

            modelBuilder.Entity("Model.PN.Model.PutniNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKraja")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datum_kraja");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datum_pocetka");

                    b.Property<int>("MjestoPutovanja")
                        .HasColumnType("integer")
                        .HasColumnName("mjesto_putovanja_id");

                    b.Property<int>("Vozilo")
                        .HasColumnType("integer")
                        .HasColumnName("vozilo_id");

                    b.Property<int>("Zaposlenik")
                        .HasColumnType("integer")
                        .HasColumnName("zaposlenik_id");

                    b.HasKey("Id");

                    b.ToTable("putni_nalog");
                });

            modelBuilder.Entity("Model.PN.Model.PutniTroskovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("IznosTroska")
                        .HasColumnType("double precision")
                        .HasColumnName("iznos_troska");

                    b.Property<int>("VrstaTroska")
                        .HasColumnType("integer")
                        .HasColumnName("vrsta_troska_id");

                    b.HasKey("Id");

                    b.ToTable("putni_troskovi");
                });

            modelBuilder.Entity("Model.PN.Model.RadnoMjesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text")
                        .HasColumnName("naziv");

                    b.HasKey("Id");

                    b.ToTable("radno_mjesto");
                });

            modelBuilder.Entity("Model.PN.Model.Vozilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Marka")
                        .HasColumnType("text")
                        .HasColumnName("marka");

                    b.Property<string>("Registracija")
                        .HasColumnType("text")
                        .HasColumnName("registracija");

                    b.HasKey("Id");

                    b.ToTable("vozilo");
                });

            modelBuilder.Entity("Model.PN.Model.VrstaTroska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text")
                        .HasColumnName("naziv");

                    b.HasKey("Id");

                    b.ToTable("vrsta_troska");
                });

            modelBuilder.Entity("Model.PN.Model.Zaposlenik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .HasColumnType("text")
                        .HasColumnName("ime");

                    b.Property<string>("Prezime")
                        .HasColumnType("text")
                        .HasColumnName("prezime");

                    b.Property<int>("PutniTroskovi")
                        .HasColumnType("integer")
                        .HasColumnName("putni_troskovi_id");

                    b.Property<int>("RadnoMjesto")
                        .HasColumnType("integer")
                        .HasColumnName("radno_mjesto_id");

                    b.Property<double?>("UkupniIznosTroska")
                        .HasColumnType("double precision")
                        .HasColumnName("ukupni_iznos_troska");

                    b.HasKey("Id");

                    b.ToTable("zaposlenik");
                });
#pragma warning restore 612, 618
        }
    }
}
